name: Generate Interactive 3D STL

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 6 PM UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-skyline
    steps:
      - uses: actions/checkout@v3

      - name: Generate Skyline STL
        run: |
          gh extension install github/gh-skyline
          # Explicitly naming the output file in the current directory
          gh skyline --user tanaytr --year 2025 tanaytr-2025-skyline.stl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Logic to check if file exists before attempting commit
          if [ -f "tanaytr-2025-skyline.stl" ]; then
            git add tanaytr-2025-skyline.stl
            git commit -m "Update 3D Skyline STL"
            git push
          else
            echo "Error: tanaytr-2025-skyline.stl not found!"
            exit 1
          fi
